set(TMP_DIR "${CMAKE_CURRENT_BINARY_DIR}/linclust_reps_tmp")
set(CLUSTERS_FILE "${TMP_DIR}/clusters.tsv")
set(REPS_FILE "${TMP_DIR}/reps.faa")

file(REMOVE_RECURSE "${TMP_DIR}")
file(MAKE_DIRECTORY "${TMP_DIR}")

set(CMD "./diamond linclust -d ${TEST_DIR}/1.faa -p1 --approx-id 0 --cluster-steps faster_lin -o ${CLUSTERS_FILE} --reps ${REPS_FILE}")
separate_arguments(SEP NATIVE_COMMAND "${CMD}")
execute_process(COMMAND ${SEP} RESULT_VARIABLE CMD_RESULT)
if(NOT ${CMD_RESULT} EQUAL 0)
  message(FATAL_ERROR "linclust_reps command failed.")
endif()

file(STRINGS "${REPS_FILE}" REP_HEADERS REGEX "^>")
list(LENGTH REP_HEADERS REP_COUNT)
if(NOT REP_COUNT EQUAL 1)
  message(FATAL_ERROR "linclust_reps expected exactly 1 representative, got ${REP_COUNT}.")
endif()

list(GET REP_HEADERS 0 FIRST_HEADER)
if(NOT FIRST_HEADER STREQUAL ">NP_001001178.1")
  message(FATAL_ERROR "linclust_reps expected FASTA header >NP_001001178.1, got ${FIRST_HEADER}.")
endif()

set(CLUSTER_COUNT 0)
file(STRINGS "${CLUSTERS_FILE}" CLUSTER_LINES)
foreach(LINE IN LISTS CLUSTER_LINES)
  string(REPLACE "\t" ";" FIELDS "${LINE}")
  list(LENGTH FIELDS FIELD_COUNT)
  if(FIELD_COUNT GREATER 1)
    list(GET FIELDS 0 REP_ID)
    list(GET FIELDS 1 MEMBER_ID)
    if(REP_ID STREQUAL MEMBER_ID)
      math(EXPR CLUSTER_COUNT "${CLUSTER_COUNT} + 1")
    endif()
  endif()
endforeach()

if(NOT CLUSTER_COUNT EQUAL REP_COUNT)
  message(FATAL_ERROR "linclust_reps representative count ${REP_COUNT} did not match cluster count ${CLUSTER_COUNT}.")
endif()

file(REMOVE_RECURSE "${TMP_DIR}")
